version: '3'

tasks:
  default:
    cmds:
      - nix flake check --all-systems

  nixos-rebuild:
    internal: true
    cmds:
      - nixos-rebuild {{.ACTION}} --elevate=sudo --no-reexec --build-host {{.BUILD_HOST}} --target-host {{.TARGET_HOST}} --flake {{.FLAKE_URI}}

  switch:brim:
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: switch
          BUILD_HOST: nixos@join.brim.su
          TARGET_HOST: nixos@join.brim.su
          FLAKE_URI: .#brim

  boot:brim:
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: boot
          BUILD_HOST: nixos@join.brim.su
          TARGET_HOST: nixos@join.brim.su
          FLAKE_URI: .#brim

  check:brim:
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: dry-activate
          BUILD_HOST: nixos@join.brim.su
          TARGET_HOST: nixos@join.brim.su
          FLAKE_URI: .#brim

  build:brim:
    cmds:
      - task: nixos-rebuild
        vars:
          ACTION: build
          BUILD_HOST: nixos@join.brim.su
          TARGET_HOST: nixos@join.brim.su
          FLAKE_URI: .#brim
